In [1]:
import json
from pathlib import Path
import polars as pl
from IPython.display import Markdown

In [2]:
from pan26_genai_detection.evaluator.evaluator import c_at_1, auc, f1, f05u, brier_score

def evaluate_all(y_true: pl.DataFrame, y_pred: pl.DataFrame):
    y_true = y_true.to_numpy()
    y_pred = y_pred.to_numpy()
    return pl.from_dict({
        'roc-auc': auc(y_true, y_pred),
        'brier': brier_score(y_true, y_pred),
        'c@1': c_at_1(y_true, y_pred),
        'f1': f1(y_true, y_pred),
        'f05u': f05u(y_true, y_pred),
    }).with_columns(
        pl.mean_horizontal(pl.all()).alias('mean'),
        pl.lit((y_pred[y_true == 0] >= 0.5).sum() / (y_true == 0).sum()).alias('fpr'),
        pl.lit((y_pred[y_true == 1] < 0.5).sum() / (y_true == 1).sum()).alias('fnr'),
    )

In [3]:
def build_truth_map(truth_file: Path, id_map_file: Path = None):
    truth_df = pl.read_ndjson(truth_file)
    if not id_map_file:
        return truth_df.with_columns(pl.lit(None).alias('orig_id'))
    id_map_df = pl.read_ndjson(id_map_file)
    return truth_df.join(id_map_df, on='id', how='left')

def load_run_files(rundir: Path):
    meta_df = pl.read_ndjson(rundir / 'metadata.jsonl')
    runs_df = []
    run_ids = meta_df.select('run_id').unique().to_series()

    # Leave no stray runs behind
    assert len(run_ids) == len(list(rundir.joinpath('outputs-flat').glob('2026-*')))

    for rid in run_ids:
        runfile = rundir / 'outputs-flat' / rid
        for l in runfile.open('r'):
            j = json.loads(l)
            j['run_id'] = rid
            runs_df.append(j)

    df = pl.from_records(runs_df)
    df = df.join(meta_df.select(['run_id', 'team', 'software', 'dataset']), on='run_id', how='left')
    return df

def join_runs_and_truth(runs_df: pl.DataFrame, meta_df: pl.DataFrame):
    df = runs_df.join(meta_df, on='id', how='left')
    df = df.rename({'label': 'label_pred', 'label_right': 'label_truth'})

    # Sanity check
    assert df['label_truth'].is_not_null().all()
    assert df['label_pred'].is_not_null().all()

    # Reorder columns and sort
    col_order = ['team', 'software', 'run_id', 'id', 'orig_id', 'model', 'source', 'label_pred', 'label_truth', 'dataset']
    df = df.select(col_order)
    df = df.sort(by=['team', 'software', 'run_id', 'model', 'label_truth'])
    return df

def load_run_truth_and_meta(base_path, truth_file, id_map_file=None):
    truth_map_pan26 = build_truth_map(truth_file, id_map_file)
    runs_pan26 = load_run_files(base_path)
    return join_runs_and_truth(runs_pan26, truth_map_pan26)

In [4]:
BASE_PATH = Path('../data')
BASE_EVAL_PATH = BASE_PATH / 'task-eval'
BASE_RUN_PATH = BASE_EVAL_PATH / 'tira-runs'

In [5]:
pan25_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan25',
                                   BASE_PATH / 'splits' / 'pan25-voight-kampff-test-truth.jsonl')
pan25_df

shape: (731_085, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 440ff192- ┆ … ┆ riddell-j ┆ 0.720498  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ f174-59ec ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8266-da8 ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ bca…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ aeb851b0- ┆ … ┆ gutenberg ┆ 0.719775  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ c06b-54ba ┆   ┆ -19c-fict ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b645-14b ┆   ┆ ion       ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 5df…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 7a9ba40a- ┆ … ┆ gutenberg ┆ 0.710772  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ e4e0-5375 ┆   ┆ -19c-fict ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9f20-fa4 ┆   ┆ ion       ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 3e2…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 79dcf967- ┆ … ┆ brennan-g ┆ 0.718746  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ b620-5fca ┆   ┆ reenstadt ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9a1c-4e3 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ b42…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 85e38931- ┆ … ┆ brennan-g ┆ 0.722734  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ bb41-5f11 ┆   ┆ reenstadt ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -898e-fd7 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ dd2…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ cd0a01a2- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 69c8-5c43 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8785-dd7 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 748…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ e11abbfa- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ a99c-55a4 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -850f-0f9 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 957…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 25f67501- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 5396-5d44 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -9681-921 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 803…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 25ce1cf1- ┆ … ┆ pan24-tes ┆ 0.999996  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 6502-589f ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8e93-052 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ dc7…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 30c34c83- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 622d-5ea0 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8fad-79b ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 7e8…      ┆   ┆           ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
pan26_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan26',
                                   BASE_PATH / 'splits' / 'pan26-voight-kampff-test-truth.jsonl',
                                   BASE_PATH / 'sampled' / 'pan26-voight-kampff-orig-ids.jsonl')
pan26_df

shape: (304_567, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ c64c7947- ┆ … ┆ nytimes-w ┆ 0.71872   ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 05e9-5826 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -aaef-8f9 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 557…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ a6d5ce11- ┆ … ┆ nytimes-w ┆ 0.719311  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 948f-5935 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -9319-ee4 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 509…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 313df7ca- ┆ … ┆ nytimes-w ┆ 0.719734  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ dfb1-5770 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -8d10-533 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 17d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 8972c72b- ┆ … ┆ nytimes-w ┆ 0.719496  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 4069-5792 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -939f-d87 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ ac2…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 60cb984e- ┆ … ┆ nytimes-w ┆ 0.718834  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ b516-5d3b ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -8ff4-6bb ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 8fa…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ e512c65e- ┆ … ┆ nytimes-w ┆ 0.00082   ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ f51a-551c ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9f19-b57 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ b12…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ b439cb5e- ┆ … ┆ nytimes-w ┆ 0.000237  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ e7e0-5f85 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8404-de5 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 408…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ b247c664- ┆ … ┆ nytimes-w ┆ 0.000316  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ e1f4-5dd6 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -a20f-88a ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 553…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ b2044bdd- ┆ … ┆ nytimes-w ┆ 0.000178  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 7cbf-5ced ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9a74-a99 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 9b9…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 9faef726- ┆ … ┆ nytimes-w ┆ 0.000229  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 61a0-5f96 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9a3f-180 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 2c0…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
def get_results_per_run(df):
    group_cols = ['team', 'software', 'run_id', 'dataset']

    def evaluate_group(key, group_df):
        metrics = evaluate_all(
            group_df.select('label_truth'),
            group_df.select('label_pred'),
        )
        keys = pl.DataFrame([dict(zip(group_cols, key))])
        return pl.concat([keys, metrics], how='horizontal')

    return pl.concat(
        evaluate_group(key, group_df)
        for key, group_df in df.partition_by(
            group_cols,
            as_dict=True,
            maintain_order=True,
        ).items()
    ).sort(by='mean', descending=True)

def get_best_by_team(result_per_run_df, with_baselines=True):
    best_by_team = result_per_run_df.filter(pl.col('team') != 'baseline').unique(subset='team', keep='first', maintain_order=True)
    if not with_baselines:
        return best_by_team

    baseline_runs = result_per_run_df.filter(pl.col('team') == 'baseline')
    return pl.concat([best_by_team, baseline_runs]).sort('mean', descending=True).drop('run_id')

In [13]:
results_per_run25 = get_results_per_run(pan25_df)
results_per_run26 = get_results_per_run(pan26_df)

In [11]:
display(Markdown('# PAN\'25 Dataset:'))
with pl.Config(float_precision=3, tbl_rows=-1):
    display(get_best_by_team(results_per_run25))

# PAN'25 Dataset:

shape: (35, 11)
┌─────────────────┬─────────────────┬────────────────┬─────────┬───┬───────┬───────┬───────┬───────┐
│ team            ┆ software        ┆ dataset        ┆ roc-auc ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---             ┆ ---             ┆ ---            ┆ ---     ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str             ┆ str             ┆ str            ┆ f64     ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞═════════════════╪═════════════════╪════════════════╪═════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ mdok            ┆ mdok            ┆ pan25-generati ┆ 0.997   ┆ … ┆ 0.994 ┆ 0.991 ┆ 0.006 ┆ 0.017 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ plagiarism-dete ┆ alternating-con ┆ pan25-generati ┆ 0.999   ┆ … ┆ 0.992 ┆ 0.988 ┆ 0.001 ┆ 0.024 │
│ ctor-com-reg2   ┆ tingency        ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ turingteam      ┆ marinated-edge  ┆ pan25-generati ┆ 0.995   ┆ … ┆ 0.991 ┆ 0.986 ┆ 0.010 ┆ 0.025 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ dsgt-pan-26     ┆ relaxed-copy    ┆ pan25-generati ┆ 0.998   ┆ … ┆ 0.990 ┆ 0.983 ┆ 0.005 ┆ 0.038 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ suspiciously-co ┆ lead-log        ┆ pan25-generati ┆ 0.998   ┆ … ┆ 0.967 ┆ 0.979 ┆ 0.098 ┆ 0.001 │
│ herent          ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ styloch2026     ┆ instant-tartar  ┆ pan25-generati ┆ 0.988   ┆ … ┆ 0.989 ┆ 0.977 ┆ 0.003 ┆ 0.048 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ sst             ┆ DeBERTa-V3-larg ┆ pan25-generati ┆ 0.987   ┆ … ┆ 0.987 ┆ 0.977 ┆ 0.010 ┆ 0.045 │
│                 ┆ e-individual    ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ak-ys           ┆ Qwen3-0.6B-fine ┆ pan25-generati ┆ 0.991   ┆ … ┆ 0.982 ┆ 0.968 ┆ 0.009 ┆ 0.069 │
│                 ┆ -tuned          ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆ (dockerf…       ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ zhengqiaozeng   ┆ three           ┆ pan25-generati ┆ 0.978   ┆ … ┆ 0.976 ┆ 0.952 ┆ 0.006 ┆ 0.099 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ikr3            ┆ lexical +       ┆ pan25-generati ┆ 0.978   ┆ … ┆ 0.974 ┆ 0.952 ┆ 0.008 ┆ 0.104 │
│                 ┆ semantic avg    ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ momifai         ┆ molten-deck     ┆ pan25-generati ┆ 0.981   ┆ … ┆ 0.974 ┆ 0.948 ┆ 0.006 ┆ 0.109 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ codingmates     ┆ immediate-chimi ┆ pan25-generati ┆ 0.973   ┆ … ┆ 0.961 ┆ 0.947 ┆ 0.055 ┆ 0.089 │
│                 ┆ changa          ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ writerslogic-in ┆ large-rank      ┆ pan25-generati ┆ 0.979   ┆ … ┆ 0.959 ┆ 0.946 ┆ 0.061 ┆ 0.091 │
│ c               ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ nai-long-zhan-d ┆ solid-capital   ┆ pan25-generati ┆ 0.973   ┆ … ┆ 0.970 ┆ 0.945 ┆ 0.016 ┆ 0.111 │
│ ui              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ team-uit-huyygi ┆ nice-frequency  ┆ pan25-generati ┆ 0.980   ┆ … ┆ 0.969 ┆ 0.944 ┆ 0.015 ┆ 0.113 │
│ aa              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ a-a-detection   ┆ navy-iceberg    ┆ pan25-generati ┆ 0.982   ┆ … ┆ 0.952 ┆ 0.944 ┆ 0.111 ┆ 0.048 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ xlbn            ┆ Grace           ┆ pan25-generati ┆ 0.969   ┆ … ┆ 0.968 ┆ 0.941 ┆ 0.013 ┆ 0.119 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ baseline        ┆ baseline-tf-idf ┆ pan25-generati ┆ 0.970   ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.090 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ nexo            ┆ skinny-pigeon   ┆ pan25-generati ┆ 0.971   ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.106 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ chat-only       ┆ mashed-sweeper  ┆ pan25-generati ┆ 0.971   ┆ … ┆ 0.968 ┆ 0.939 ┆ 0.006 ┆ 0.131 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ aitestchecking  ┆ nullary-velocit ┆ pan25-generati ┆ 0.965   ┆ … ┆ 0.967 ┆ 0.938 ┆ 0.011 ┆ 0.129 │
│                 ┆ y               ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ latentauthors   ┆ roaring-assuran ┆ pan25-generati ┆ 0.960   ┆ … ┆ 0.970 ┆ 0.937 ┆ 0.005 ┆ 0.127 │
│                 ┆ ce              ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ydong           ┆ arid-winch      ┆ pan25-generati ┆ 0.966   ┆ … ┆ 0.935 ┆ 0.937 ┆ 0.155 ┆ 0.063 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ce-ec           ┆ flavorful-raisi ┆ pan25-generati ┆ 0.959   ┆ … ┆ 0.960 ┆ 0.935 ┆ 0.043 ┆ 0.112 │
│                 ┆ n               ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ adnan-riad      ┆ Adv_E8_0.3      ┆ pan25-generati ┆ 0.966   ┆ … ┆ 0.960 ┆ 0.933 ┆ 0.036 ┆ 0.122 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ spj             ┆ wintry-burger   ┆ pan25-generati ┆ 0.952   ┆ … ┆ 0.968 ┆ 0.931 ┆ 0.004 ┆ 0.137 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ egrantha-ai     ┆ finite-velour   ┆ pan25-generati ┆ 0.931   ┆ … ┆ 0.968 ┆ 0.929 ┆ 0.010 ┆ 0.128 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ odean           ┆ narrow-lamb     ┆ pan25-generati ┆ 0.929   ┆ … ┆ 0.966 ┆ 0.928 ┆ 0.017 ┆ 0.124 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ original        ┆ central-range   ┆ pan25-generati ┆ 0.933   ┆ … ┆ 0.963 ┆ 0.925 ┆ 0.014 ┆ 0.141 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ manexagirrezaba ┆ adventurous-dra ┆ pan25-generati ┆ 0.947   ┆ … ┆ 0.954 ┆ 0.922 ┆ 0.038 ┆ 0.142 │
│ l               ┆ wbridge         ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ shushantatudubl ┆ accepting-cut   ┆ pan25-generati ┆ 0.941   ┆ … ┆ 0.957 ┆ 0.919 ┆ 0.024 ┆ 0.149 │
│ in              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ yjl             ┆ antique-impulse ┆ pan25-generati ┆ 0.945   ┆ … ┆ 0.949 ┆ 0.905 ┆ 0.021 ┆ 0.184 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ uned-martinez   ┆ current-line    ┆ pan25-generati ┆ 0.933   ┆ … ┆ 0.881 ┆ 0.891 ┆ 0.333 ┆ 0.077 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ baseline        ┆ baseline-ppmd   ┆ pan25-generati ┆ 0.723   ┆ … ┆ 0.780 ┆ 0.765 ┆ 0.627 ┆ 0.124 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ yihao           ┆ clear-buyer     ┆ pan25-generati ┆ 0.500   ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
└─────────────────┴─────────────────┴────────────────┴─────────┴───┴───────┴───────┴───────┴───────┘

In [12]:
display(Markdown('# PAN\'26 Dataset:'))
with pl.Config(float_precision=3, tbl_rows=-1):
    display(get_best_by_team(results_per_run26))

# PAN'26 Dataset:

shape: (36, 11)
┌─────────────────┬─────────────────┬────────────────┬─────────┬───┬───────┬───────┬───────┬───────┐
│ team            ┆ software        ┆ dataset        ┆ roc-auc ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---             ┆ ---             ┆ ---            ┆ ---     ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str             ┆ str             ┆ str            ┆ f64     ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞═════════════════╪═════════════════╪════════════════╪═════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ suspiciously-co ┆ lead-log        ┆ pan26-generati ┆ 0.989   ┆ … ┆ 0.980 ┆ 0.975 ┆ 0.053 ┆ 0.029 │
│ herent          ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ sst             ┆ ModernBERT-larg ┆ pan26-generati ┆ 0.993   ┆ … ┆ 0.969 ┆ 0.974 ┆ 0.108 ┆ 0.014 │
│                 ┆ e-BNN           ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ mdok            ┆ mdok            ┆ pan26-generati ┆ 0.995   ┆ … ┆ 0.984 ┆ 0.968 ┆ 0.002 ┆ 0.072 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ plagiarism-dete ┆ alternating-con ┆ pan26-generati ┆ 0.996   ┆ … ┆ 0.957 ┆ 0.946 ┆ 0.000 ┆ 0.072 │
│ ctor-com-reg2   ┆ tingency        ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ dsgt-pan-26     ┆ relaxed-copy    ┆ pan26-generati ┆ 0.981   ┆ … ┆ 0.961 ┆ 0.921 ┆ 0.000 ┆ 0.170 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ydong           ┆ arid-winch      ┆ pan26-generati ┆ 0.930   ┆ … ┆ 0.896 ┆ 0.911 ┆ 0.420 ┆ 0.014 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ turingteam      ┆ marinated-edge  ┆ pan26-generati ┆ 0.957   ┆ … ┆ 0.925 ┆ 0.892 ┆ 0.053 ┆ 0.179 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ writerslogic-in ┆ large-rank      ┆ pan26-generati ┆ 0.891   ┆ … ┆ 0.899 ┆ 0.887 ┆ 0.312 ┆ 0.092 │
│ c               ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ a-a-detection   ┆ navy-iceberg    ┆ pan26-generati ┆ 0.852   ┆ … ┆ 0.880 ┆ 0.858 ┆ 0.375 ┆ 0.106 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ baseline        ┆ baseline-ppmd   ┆ pan26-generati ┆ 0.783   ┆ … ┆ 0.828 ┆ 0.814 ┆ 0.728 ┆ 0.066 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ak-ys           ┆ Qwen3-14B-fine- ┆ pan26-generati ┆ 0.911   ┆ … ┆ 0.891 ┆ 0.811 ┆ 0.016 ┆ 0.365 │
│                 ┆ tuned           ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ikr3            ┆ lexical +       ┆ pan26-generati ┆ 0.814   ┆ … ┆ 0.788 ┆ 0.797 ┆ 1.000 ┆ 0.000 │
│                 ┆ linguistic LR   ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ ce-ec           ┆ atomic-fruit    ┆ pan26-generati ┆ 0.624   ┆ … ┆ 0.788 ┆ 0.757 ┆ 1.000 ┆ 0.001 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ egrantha-ai     ┆ faded-noir      ┆ pan26-generati ┆ 0.500   ┆ … ┆ 0.788 ┆ 0.728 ┆ 1.000 ┆ 0.000 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ odean           ┆ narrow-lamb     ┆ pan26-generati ┆ 0.732   ┆ … ┆ 0.823 ┆ 0.695 ┆ 0.051 ┆ 0.485 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ codingmates     ┆ silent-screen   ┆ pan26-generati ┆ 0.756   ┆ … ┆ 0.768 ┆ 0.687 ┆ 0.178 ┆ 0.448 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ adnan-riad      ┆ ADV_05_new      ┆ pan26-generati ┆ 0.856   ┆ … ┆ 0.764 ┆ 0.682 ┆ 0.036 ┆ 0.588 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ styloch2026     ┆ instant-tartar  ┆ pan26-generati ┆ 0.931   ┆ … ┆ 0.744 ┆ 0.662 ┆ 0.002 ┆ 0.632 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ momifai         ┆ molten-deck     ┆ pan26-generati ┆ 0.867   ┆ … ┆ 0.744 ┆ 0.645 ┆ 0.024 ┆ 0.621 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ team-uit-huyygi ┆ nice-frequency  ┆ pan26-generati ┆ 0.779   ┆ … ┆ 0.756 ┆ 0.638 ┆ 0.018 ┆ 0.609 │
│ aa              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ shushantatudubl ┆ similar-factor  ┆ pan26-generati ┆ 0.856   ┆ … ┆ 0.708 ┆ 0.632 ┆ 0.014 ┆ 0.668 │
│ in              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ yjl             ┆ antique-impulse ┆ pan26-generati ┆ 0.649   ┆ … ┆ 0.751 ┆ 0.615 ┆ 0.075 ┆ 0.585 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ uned-martinez   ┆ current-line    ┆ pan26-generati ┆ 0.603   ┆ … ┆ 0.700 ┆ 0.604 ┆ 0.274 ┆ 0.563 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ manexagirrezaba ┆ adventurous-dra ┆ pan26-generati ┆ 0.711   ┆ … ┆ 0.692 ┆ 0.601 ┆ 0.061 ┆ 0.664 │
│ l               ┆ wbridge         ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ xlbn            ┆ Grace           ┆ pan26-generati ┆ 0.792   ┆ … ┆ 0.674 ┆ 0.593 ┆ 0.028 ┆ 0.671 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ chat-only       ┆ mashed-sweeper  ┆ pan26-generati ┆ 0.801   ┆ … ┆ 0.669 ┆ 0.591 ┆ 0.022 ┆ 0.704 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ original        ┆ central-range   ┆ pan26-generati ┆ 0.681   ┆ … ┆ 0.708 ┆ 0.590 ┆ 0.016 ┆ 0.648 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ baseline        ┆ baseline-tf-idf ┆ pan26-generati ┆ 0.711   ┆ … ┆ 0.637 ┆ 0.586 ┆ 0.069 ┆ 0.651 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ nexo            ┆ skinny-pigeon   ┆ pan26-generati ┆ 0.651   ┆ … ┆ 0.703 ┆ 0.580 ┆ 0.075 ┆ 0.638 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ aitestchecking  ┆ nullary-velocit ┆ pan26-generati ┆ 0.802   ┆ … ┆ 0.645 ┆ 0.577 ┆ 0.006 ┆ 0.731 │
│                 ┆ y               ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ nai-long-zhan-d ┆ solid-capital   ┆ pan26-generati ┆ 0.690   ┆ … ┆ 0.670 ┆ 0.570 ┆ 0.055 ┆ 0.668 │
│ ui              ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ latentauthors   ┆ roaring-assuran ┆ pan26-generati ┆ 0.750   ┆ … ┆ 0.678 ┆ 0.569 ┆ 0.008 ┆ 0.701 │
│                 ┆ ce              ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ zhengqiaozeng   ┆ three           ┆ pan26-generati ┆ 0.753   ┆ … ┆ 0.661 ┆ 0.556 ┆ 0.002 ┆ 0.719 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ spj             ┆ wintry-burger   ┆ pan26-generati ┆ 0.772   ┆ … ┆ 0.620 ┆ 0.532 ┆ 0.000 ┆ 0.754 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ baseline        ┆ baseline-binocu ┆ pan26-generati ┆ 0.681   ┆ … ┆ 0.422 ┆ 0.455 ┆ 0.012 ┆ 0.863 │
│                 ┆ lars-tiny-llama ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
│ yihao           ┆ clear-buyer     ┆ pan26-generati ┆ 0.500   ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
│                 ┆                 ┆ ve-ai-detectio ┆         ┆   ┆       ┆       ┆       ┆       │
│                 ┆                 ┆ n-…            ┆         ┆   ┆       ┆       ┆       ┆       │
└─────────────────┴─────────────────┴────────────────┴─────────┴───┴───────┴───────┴───────┴───────┘