In [1]:
import json
from pathlib import Path
import polars as pl
from IPython.display import Markdown
from polars import DataFrame, LazyFrame

In [2]:
from pan26_genai_detection.evaluator.evaluator import c_at_1, auc, f1, f05u, brier_score

def evaluate_all(y_true: pl.DataFrame, y_pred: pl.DataFrame):
    y_true = y_true.to_numpy()
    y_pred = y_pred.to_numpy()
    return pl.from_dict({
        'roc-auc': auc(y_true, y_pred),
        'brier': brier_score(y_true, y_pred),
        'c@1': c_at_1(y_true, y_pred),
        'f1': f1(y_true, y_pred),
        'f05u': f05u(y_true, y_pred),
    }).with_columns(
        pl.mean_horizontal(pl.all()).alias('mean'),
        pl.lit((y_pred[y_true == 0] >= 0.5).sum() / (y_true == 0).sum()).alias('fpr'),
        pl.lit((y_pred[y_true == 1] < 0.5).sum() / (y_true == 1).sum()).alias('fnr'),
    )

In [3]:
def build_truth_map(truth_file: Path, id_map_file: Path = None):
    truth_df = pl.read_ndjson(truth_file)
    if not id_map_file:
        return truth_df.with_columns(pl.lit(None).alias('orig_id'))
    id_map_df = pl.read_ndjson(id_map_file)
    return truth_df.join(id_map_df, on='id', how='left')

def load_run_files(rundir: Path):
    meta_df = pl.read_ndjson(rundir / 'metadata.jsonl')
    runs_df = []
    run_ids = meta_df.select('run_id').unique().to_series()

    # Leave no stray runs behind
    assert len(run_ids) == len(list(rundir.joinpath('outputs-flat').glob('2026-*')))

    for rid in run_ids:
        runfile = rundir / 'outputs-flat' / rid
        for l in runfile.open('r'):
            j = json.loads(l)
            j['run_id'] = rid
            runs_df.append(j)

    df = pl.from_records(runs_df)
    df = df.join(meta_df.select(['run_id', 'team', 'software', 'dataset']), on='run_id', how='left')
    return df

def join_runs_and_truth(runs_df: pl.DataFrame, meta_df: pl.DataFrame):
    df = runs_df.join(meta_df, on='id', how='left')
    df = df.rename({'label': 'label_pred', 'label_right': 'label_truth'})

    # Sanity check
    assert df['label_truth'].is_not_null().all()
    assert df['label_pred'].is_not_null().all()

    # Reorder columns and sort
    col_order = ['team', 'software', 'run_id', 'id', 'orig_id', 'model', 'source', 'label_pred', 'label_truth', 'dataset']
    df = df.select(col_order)
    df = df.sort(by=['team', 'software', 'run_id', 'model', 'label_truth'])
    return df

def load_run_truth_and_meta(base_path, truth_file, id_map_file=None):
    truth_map_pan26 = build_truth_map(truth_file, id_map_file)
    runs_pan26 = load_run_files(base_path)
    return join_runs_and_truth(runs_pan26, truth_map_pan26)

In [4]:
BASE_PATH = Path('../data')
BASE_EVAL_PATH = BASE_PATH / 'task-eval'
BASE_RUN_PATH = BASE_EVAL_PATH / 'tira-runs'

In [5]:
pan25_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan25',
                                   BASE_PATH / 'splits' / 'pan25-voight-kampff-test-truth.jsonl')
pan25_df

shape: (731_085, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ d1c70c8c- ┆ … ┆ riddell-j ┆ 0.720491  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 3ff0-5305 ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b385-295 ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 330…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 395d524d- ┆ … ┆ brennan-g ┆ 0.722011  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 0fc6-5051 ┆   ┆ reenstadt ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8c36-9b0 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ f7b…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 5dcd62b6- ┆ … ┆ riddell-j ┆ 0.721599  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 7540-5a93 ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -9a49-073 ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 00c…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 6d87c56f- ┆ … ┆ gutenberg ┆ 0.665258  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ deca-5778 ┆   ┆ -19c-fict ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -92f2-7fb ┆   ┆ ion       ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 7c7…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 2925298b- ┆ … ┆ gutenberg ┆ 0.69028   ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ ad01-56e6 ┆   ┆ -19c-fict ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -a180-883 ┆   ┆ ion       ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 45f…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ ccbba8d3- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ f1a4-5acc ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -851d-2a1 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 539…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 8425bf1c- ┆ … ┆ pan24-tes ┆ 0.999995  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ f2ed-5fdf ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -9966-14a ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 2f6…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ cd0a01a2- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 69c8-5c43 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8785-dd7 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 748…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 90de9dca- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ bb77-5d6c ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -945c-e07 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 79d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 30c34c83- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 622d-5ea0 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8fad-79b ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 7e8…      ┆   ┆           ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
pan26_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan26',
                                   BASE_PATH / 'splits' / 'pan26-voight-kampff-test-truth.jsonl',
                                   BASE_PATH / 'sampled' / 'pan26-voight-kampff-orig-ids.jsonl')
pan26_df

shape: (304_567, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 73af25da- ┆ … ┆ nytimes-w ┆ 0.71923   ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ c3a1-56ba ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -a713-a75 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ f43…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 5f3b43a2- ┆ … ┆ nytimes-w ┆ 0.718736  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ d8c5-53d5 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -ae7e-288 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ e53…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 7156fd07- ┆ … ┆ nytimes-w ┆ 0.721251  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 36b5-54be ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -85c9-941 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 0d9…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 66c5dea1- ┆ … ┆ nytimes-w ┆ 0.718389  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 7efd-5c7b ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -9a05-653 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ f1e…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 35158c56- ┆ … ┆ nytimes-w ┆ 0.719686  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 1389-57ca ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -b997-dfb ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 9dc…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 10cc6cc9- ┆ … ┆ nytimes-w ┆ 0.000294  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 0222-5fb5 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b9cc-8d2 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 784…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ a6d3ffd4- ┆ … ┆ nytimes-w ┆ 0.000143  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ bf80-5005 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -bbc8-c8f ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ e14…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 26983fba- ┆ … ┆ nytimes-w ┆ 0.000163  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ fd6f-5f7b ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b4b0-411 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ ff8…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ c2cc62b8- ┆ … ┆ nytimes-w ┆ 0.000242  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ dec1-5a57 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -bb8a-613 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 6e4…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 71afa547- ┆ … ┆ nytimes-w ┆ 0.000153  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 97e0-540d ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b913-67b ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ c09…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
def get_results_per_run(df):
    group_cols = ['team', 'software', 'run_id', 'dataset']

    def evaluate_group(key, group_df):
        metrics = evaluate_all(
            group_df.select('label_truth'),
            group_df.select('label_pred'),
        )
        keys = pl.DataFrame([dict(zip(group_cols, key))])
        return pl.concat([keys, metrics], how='horizontal')

    return pl.concat(
        evaluate_group(key, group_df)
        for key, group_df in df.partition_by(
            group_cols,
            as_dict=True,
            maintain_order=True,
        ).items()
    ).sort(by='mean', descending=True)

def get_best_by_team(result_per_run_df, with_baselines=True):
    best_by_team = result_per_run_df.filter(pl.col('team') != 'baseline').unique(subset='team', keep='first', maintain_order=True)
    if not with_baselines:
        return best_by_team

    baseline_runs = result_per_run_df.filter(pl.col('team') == 'baseline')
    return pl.concat([best_by_team, baseline_runs]).sort('mean', descending=True).drop('run_id')

In [8]:
results_per_run25 = get_results_per_run(pan25_df)
results_per_run26 = get_results_per_run(pan26_df)

In [9]:
display(Markdown('# PAN\'25 Dataset:'))
with pl.Config(float_precision=3, tbl_rows=-1):
    display(get_best_by_team(results_per_run25).drop('dataset'))

# PAN'25 Dataset:

shape: (35, 10)
┌──────────────────────┬─────────────────────┬─────────┬───────┬───┬───────┬───────┬───────┬───────┐
│ team                 ┆ software            ┆ roc-auc ┆ brier ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---                  ┆ ---                 ┆ ---     ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                  ┆ str                 ┆ f64     ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞══════════════════════╪═════════════════════╪═════════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ mdok                 ┆ mdok                ┆ 0.997   ┆ 0.988 ┆ … ┆ 0.994 ┆ 0.991 ┆ 0.006 ┆ 0.017 │
│ plagiarism-detector- ┆ alternating-conting ┆ 0.999   ┆ 0.986 ┆ … ┆ 0.992 ┆ 0.988 ┆ 0.001 ┆ 0.024 │
│ com-reg2             ┆ ency                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ turingteam           ┆ marinated-edge      ┆ 0.995   ┆ 0.979 ┆ … ┆ 0.991 ┆ 0.986 ┆ 0.010 ┆ 0.025 │
│ dsgt-pan-26          ┆ relaxed-copy        ┆ 0.998   ┆ 0.977 ┆ … ┆ 0.990 ┆ 0.983 ┆ 0.005 ┆ 0.038 │
│ suspiciously-coheren ┆ lead-log            ┆ 0.998   ┆ 0.980 ┆ … ┆ 0.967 ┆ 0.979 ┆ 0.098 ┆ 0.001 │
│ t                    ┆                     ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ styloch2026          ┆ instant-tartar      ┆ 0.988   ┆ 0.967 ┆ … ┆ 0.989 ┆ 0.977 ┆ 0.003 ┆ 0.048 │
│ sst                  ┆ DeBERTa-V3-large-in ┆ 0.987   ┆ 0.969 ┆ … ┆ 0.987 ┆ 0.977 ┆ 0.010 ┆ 0.045 │
│                      ┆ dividual            ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ak-ys                ┆ Qwen3-0.6B-fine-tun ┆ 0.991   ┆ 0.957 ┆ … ┆ 0.982 ┆ 0.968 ┆ 0.009 ┆ 0.069 │
│                      ┆ ed (dockerf…        ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ zhengqiaozeng        ┆ three               ┆ 0.978   ┆ 0.931 ┆ … ┆ 0.976 ┆ 0.952 ┆ 0.006 ┆ 0.099 │
│ ikr3                 ┆ lexical + semantic  ┆ 0.978   ┆ 0.939 ┆ … ┆ 0.974 ┆ 0.952 ┆ 0.008 ┆ 0.104 │
│                      ┆ avg                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ momifai              ┆ molten-deck         ┆ 0.981   ┆ 0.922 ┆ … ┆ 0.974 ┆ 0.948 ┆ 0.006 ┆ 0.109 │
│ codingmates          ┆ immediate-chimichan ┆ 0.973   ┆ 0.939 ┆ … ┆ 0.961 ┆ 0.947 ┆ 0.055 ┆ 0.089 │
│                      ┆ ga                  ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ writerslogic-inc     ┆ large-rank          ┆ 0.979   ┆ 0.935 ┆ … ┆ 0.959 ┆ 0.946 ┆ 0.061 ┆ 0.091 │
│ nai-long-zhan-dui    ┆ solid-capital       ┆ 0.973   ┆ 0.929 ┆ … ┆ 0.970 ┆ 0.945 ┆ 0.016 ┆ 0.111 │
│ team-uit-huyygiaa    ┆ nice-frequency      ┆ 0.980   ┆ 0.919 ┆ … ┆ 0.969 ┆ 0.944 ┆ 0.015 ┆ 0.113 │
│ a-a-detection        ┆ navy-iceberg        ┆ 0.982   ┆ 0.899 ┆ … ┆ 0.952 ┆ 0.944 ┆ 0.111 ┆ 0.048 │
│ xlbn                 ┆ Grace               ┆ 0.969   ┆ 0.924 ┆ … ┆ 0.968 ┆ 0.941 ┆ 0.013 ┆ 0.119 │
│ baseline             ┆ baseline-tf-idf     ┆ 0.970   ┆ 0.918 ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.090 │
│ nexo                 ┆ skinny-pigeon       ┆ 0.971   ┆ 0.922 ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.106 │
│ chat-only            ┆ mashed-sweeper      ┆ 0.971   ┆ 0.923 ┆ … ┆ 0.968 ┆ 0.939 ┆ 0.006 ┆ 0.131 │
│ aitestchecking       ┆ nullary-velocity    ┆ 0.965   ┆ 0.922 ┆ … ┆ 0.967 ┆ 0.938 ┆ 0.011 ┆ 0.129 │
│ latentauthors        ┆ roaring-assurance   ┆ 0.960   ┆ 0.913 ┆ … ┆ 0.970 ┆ 0.937 ┆ 0.005 ┆ 0.127 │
│ ydong                ┆ arid-winch          ┆ 0.966   ┆ 0.935 ┆ … ┆ 0.935 ┆ 0.937 ┆ 0.155 ┆ 0.063 │
│ ce-ec                ┆ flavorful-raisin    ┆ 0.959   ┆ 0.914 ┆ … ┆ 0.960 ┆ 0.935 ┆ 0.043 ┆ 0.112 │
│ adnan-riad           ┆ Adv_E8_0.3          ┆ 0.966   ┆ 0.907 ┆ … ┆ 0.960 ┆ 0.933 ┆ 0.036 ┆ 0.122 │
│ spj                  ┆ wintry-burger       ┆ 0.952   ┆ 0.904 ┆ … ┆ 0.968 ┆ 0.931 ┆ 0.004 ┆ 0.137 │
│ egrantha-ai          ┆ finite-velour       ┆ 0.931   ┆ 0.908 ┆ … ┆ 0.968 ┆ 0.929 ┆ 0.010 ┆ 0.128 │
│ odean                ┆ narrow-lamb         ┆ 0.929   ┆ 0.908 ┆ … ┆ 0.966 ┆ 0.928 ┆ 0.017 ┆ 0.124 │
│ original             ┆ central-range       ┆ 0.933   ┆ 0.909 ┆ … ┆ 0.963 ┆ 0.925 ┆ 0.014 ┆ 0.141 │
│ manexagirrezabal     ┆ adventurous-drawbri ┆ 0.947   ┆ 0.906 ┆ … ┆ 0.954 ┆ 0.922 ┆ 0.038 ┆ 0.142 │
│                      ┆ dge                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ shushantatudublin    ┆ accepting-cut       ┆ 0.941   ┆ 0.893 ┆ … ┆ 0.957 ┆ 0.919 ┆ 0.024 ┆ 0.149 │
│ yjl                  ┆ antique-impulse     ┆ 0.945   ┆ 0.873 ┆ … ┆ 0.949 ┆ 0.905 ┆ 0.021 ┆ 0.184 │
│ uned-martinez        ┆ current-line        ┆ 0.933   ┆ 0.893 ┆ … ┆ 0.881 ┆ 0.891 ┆ 0.333 ┆ 0.077 │
│ baseline             ┆ baseline-ppmd       ┆ 0.723   ┆ 0.794 ┆ … ┆ 0.780 ┆ 0.765 ┆ 0.627 ┆ 0.124 │
│ yihao                ┆ clear-buyer         ┆ 0.500   ┆ 0.750 ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
└──────────────────────┴─────────────────────┴─────────┴───────┴───┴───────┴───────┴───────┴───────┘

In [11]:
display(Markdown('# PAN\'26 Dataset:'))

leaderboard26 = get_best_by_team(results_per_run26).drop('dataset')

# noinspection PyTypeChecker
zero_knowledge_pan26 = pl.from_dict({
    "team": "baseline",
    "software": "baseline-zero-knowledge",
    "roc-auc": 0.5,
    "brier": 0.749,
    "c@1": 0.749,
    "f1": 0.856,
    "f05u": 0.788,
    "mean": 0.728,
    "fpr": 1.0,
    "fnr": 0.0,
})
# noinspection PyTypeChecker
leaderboard26 = (
    pl
    .concat([leaderboard26, zero_knowledge_pan26])
    .sort('mean', descending=True)
    .with_columns([
        pl.col("team").replace("mdok", "baseline"),
        pl.col("software").replace("mdok", "baseline-mdok"),
    ])
)

leaderboard26.to_pandas().to_html(BASE_EVAL_PATH / 'pan26-leaderboard.html', index=True, float_format=lambda x: f"{x:.3f}")

with pl.Config(float_precision=3, tbl_rows=-1):
    display(leaderboard26)

# PAN'26 Dataset:

shape: (37, 10)
┌──────────────────────┬─────────────────────┬─────────┬───────┬───┬───────┬───────┬───────┬───────┐
│ team                 ┆ software            ┆ roc-auc ┆ brier ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---                  ┆ ---                 ┆ ---     ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                  ┆ str                 ┆ f64     ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞══════════════════════╪═════════════════════╪═════════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ suspiciously-coheren ┆ lead-log            ┆ 0.989   ┆ 0.965 ┆ … ┆ 0.980 ┆ 0.975 ┆ 0.053 ┆ 0.029 │
│ t                    ┆                     ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ sst                  ┆ ModernBERT-large-BN ┆ 0.993   ┆ 0.970 ┆ … ┆ 0.969 ┆ 0.974 ┆ 0.108 ┆ 0.014 │
│                      ┆ N                   ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ baseline             ┆ baseline-mdok       ┆ 0.995   ┆ 0.951 ┆ … ┆ 0.984 ┆ 0.968 ┆ 0.002 ┆ 0.072 │
│ plagiarism-detector- ┆ alternating-conting ┆ 0.996   ┆ 0.941 ┆ … ┆ 0.957 ┆ 0.946 ┆ 0.000 ┆ 0.072 │
│ com-reg2             ┆ ency                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ dsgt-pan-26          ┆ relaxed-copy        ┆ 0.981   ┆ 0.885 ┆ … ┆ 0.961 ┆ 0.921 ┆ 0.000 ┆ 0.170 │
│ ydong                ┆ arid-winch          ┆ 0.930   ┆ 0.915 ┆ … ┆ 0.896 ┆ 0.911 ┆ 0.420 ┆ 0.014 │
│ turingteam           ┆ marinated-edge      ┆ 0.957   ┆ 0.882 ┆ … ┆ 0.925 ┆ 0.892 ┆ 0.053 ┆ 0.179 │
│ writerslogic-inc     ┆ large-rank          ┆ 0.891   ┆ 0.891 ┆ … ┆ 0.899 ┆ 0.887 ┆ 0.312 ┆ 0.092 │
│ a-a-detection        ┆ navy-iceberg        ┆ 0.852   ┆ 0.848 ┆ … ┆ 0.880 ┆ 0.858 ┆ 0.375 ┆ 0.106 │
│ baseline             ┆ baseline-ppmd       ┆ 0.783   ┆ 0.810 ┆ … ┆ 0.828 ┆ 0.814 ┆ 0.728 ┆ 0.066 │
│ ak-ys                ┆ Qwen3-14B-fine-tune ┆ 0.911   ┆ 0.754 ┆ … ┆ 0.891 ┆ 0.811 ┆ 0.016 ┆ 0.365 │
│                      ┆ d                   ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ikr3                 ┆ lexical +           ┆ 0.814   ┆ 0.779 ┆ … ┆ 0.788 ┆ 0.797 ┆ 1.000 ┆ 0.000 │
│                      ┆ linguistic LR       ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ce-ec                ┆ atomic-fruit        ┆ 0.624   ┆ 0.771 ┆ … ┆ 0.788 ┆ 0.757 ┆ 1.000 ┆ 0.001 │
│ egrantha-ai          ┆ faded-noir          ┆ 0.500   ┆ 0.749 ┆ … ┆ 0.788 ┆ 0.728 ┆ 1.000 ┆ 0.000 │
│ baseline             ┆ baseline-zero-knowl ┆ 0.500   ┆ 0.749 ┆ … ┆ 0.788 ┆ 0.728 ┆ 1.000 ┆ 0.000 │
│                      ┆ edge                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ odean                ┆ narrow-lamb         ┆ 0.732   ┆ 0.624 ┆ … ┆ 0.823 ┆ 0.695 ┆ 0.051 ┆ 0.485 │
│ codingmates          ┆ silent-screen       ┆ 0.756   ┆ 0.682 ┆ … ┆ 0.768 ┆ 0.687 ┆ 0.178 ┆ 0.448 │
│ adnan-riad           ┆ ADV_05_new          ┆ 0.856   ┆ 0.658 ┆ … ┆ 0.764 ┆ 0.682 ┆ 0.036 ┆ 0.588 │
│ styloch2026          ┆ instant-tartar      ┆ 0.931   ┆ 0.572 ┆ … ┆ 0.744 ┆ 0.662 ┆ 0.002 ┆ 0.632 │
│ momifai              ┆ molten-deck         ┆ 0.867   ┆ 0.536 ┆ … ┆ 0.744 ┆ 0.645 ┆ 0.024 ┆ 0.621 │
│ team-uit-huyygiaa    ┆ nice-frequency      ┆ 0.779   ┆ 0.555 ┆ … ┆ 0.756 ┆ 0.638 ┆ 0.018 ┆ 0.609 │
│ shushantatudublin    ┆ similar-factor      ┆ 0.856   ┆ 0.602 ┆ … ┆ 0.708 ┆ 0.632 ┆ 0.014 ┆ 0.668 │
│ yjl                  ┆ antique-impulse     ┆ 0.649   ┆ 0.553 ┆ … ┆ 0.751 ┆ 0.615 ┆ 0.075 ┆ 0.585 │
│ uned-martinez        ┆ current-line        ┆ 0.603   ┆ 0.643 ┆ … ┆ 0.700 ┆ 0.604 ┆ 0.274 ┆ 0.563 │
│ manexagirrezabal     ┆ adventurous-drawbri ┆ 0.711   ┆ 0.618 ┆ … ┆ 0.692 ┆ 0.601 ┆ 0.061 ┆ 0.664 │
│                      ┆ dge                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ xlbn                 ┆ Grace               ┆ 0.792   ┆ 0.559 ┆ … ┆ 0.674 ┆ 0.593 ┆ 0.028 ┆ 0.671 │
│ chat-only            ┆ mashed-sweeper      ┆ 0.801   ┆ 0.565 ┆ … ┆ 0.669 ┆ 0.591 ┆ 0.022 ┆ 0.704 │
│ original             ┆ central-range       ┆ 0.681   ┆ 0.559 ┆ … ┆ 0.708 ┆ 0.590 ┆ 0.016 ┆ 0.648 │
│ baseline             ┆ baseline-tf-idf     ┆ 0.711   ┆ 0.686 ┆ … ┆ 0.637 ┆ 0.586 ┆ 0.069 ┆ 0.651 │
│ nexo                 ┆ skinny-pigeon       ┆ 0.651   ┆ 0.541 ┆ … ┆ 0.703 ┆ 0.580 ┆ 0.075 ┆ 0.638 │
│ aitestchecking       ┆ nullary-velocity    ┆ 0.802   ┆ 0.562 ┆ … ┆ 0.645 ┆ 0.577 ┆ 0.006 ┆ 0.731 │
│ nai-long-zhan-dui    ┆ solid-capital       ┆ 0.690   ┆ 0.549 ┆ … ┆ 0.670 ┆ 0.570 ┆ 0.055 ┆ 0.668 │
│ latentauthors        ┆ roaring-assurance   ┆ 0.750   ┆ 0.486 ┆ … ┆ 0.678 ┆ 0.569 ┆ 0.008 ┆ 0.701 │
│ zhengqiaozeng        ┆ three               ┆ 0.753   ┆ 0.464 ┆ … ┆ 0.661 ┆ 0.556 ┆ 0.002 ┆ 0.719 │
│ spj                  ┆ wintry-burger       ┆ 0.772   ┆ 0.437 ┆ … ┆ 0.620 ┆ 0.532 ┆ 0.000 ┆ 0.754 │
│ baseline             ┆ baseline-binoculars ┆ 0.681   ┆ 0.596 ┆ … ┆ 0.422 ┆ 0.455 ┆ 0.012 ┆ 0.863 │
│                      ┆ -tiny-llama         ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ yihao                ┆ clear-buyer         ┆ 0.500   ┆ 0.750 ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
└──────────────────────┴─────────────────────┴─────────┴───────┴───┴───────┴───────┴───────┴───────┘